[project]
name = "cosmogasperuser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.63.0",
    "dvc-s3>=3.2.2",
    "mlflow>=3.4.0",
    "plotly>=6.4.0",
]
